version: '3'

services:
  mongodb:
    image: mongo:6
    container_name: nestjs-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7
    container_name: nestjs-redis
    ports:
      - '6379:6379'

  nestjs-app:
    build: .
    container_name: nestjs-app
    ports:
      - '3000:3000'
    environment:
      MONGODB_URI: mongodb+srv://kanto:password1234@cluster0.olhio.mongodb.net/?retryWrites=true&w=majority&appName=Mongo
      REDIS_HOST: nestjs-redis
      REDIS_PORT: 6379
    depends_on:
      - mongodb
      - redis

  neo4j:
    image: neo4j:5
    container_name: neo4j-container
    environment:
      NEO4J_AUTH: neo4j/password1234
    ports:
      - '7687:7687'
    volumes:
      - neo4j_data:/data

  populate-db:
    build: .
    container_name: populate-db
    command: node dist/populate-db.js
    environment:
      MONGODB_URI: mongodb+srv://kanto:password1234@cluster0.olhio.mongodb.net/?retryWrites=true&w=majority&appName=Mongo
    depends_on:
      - mongodb
      - redis
      - nestjs-app
      - neo4j
    restart: "no"

volumes:
  mongodb_data:
  neo4j_data:
